.PHONY: build build-release-unsigned generate-appicons lint lint-fix-safe test clean generate-build-info

# SwiftLint: https://github.com/realm/SwiftLint — `brew install swiftlint`
SWIFTLINT ?= $(shell command -v swiftlint 2>/dev/null)

lint:
	@if [ -z "$(SWIFTLINT)" ]; then \
		echo "SwiftLint not found. Install with: brew install swiftlint" >&2; \
		exit 1; \
	fi
	@"$(SWIFTLINT)" lint --strict

# Autocorrect only low-risk rules (whitespace / file hygiene). Still review `git diff` and run tests.
# Optional: pass paths, e.g. `make lint-fix-safe FIX_PATHS="ClipboardEnvy/Foo.swift"`
FIX_PATHS ?= ClipboardEnvy ClipboardEnvyTests scripts
lint-fix-safe:
	@if [ -z "$(SWIFTLINT)" ]; then \
		echo "SwiftLint not found. Install with: brew install swiftlint" >&2; \
		exit 1; \
	fi
	@"$(SWIFTLINT)" lint --fix \
		--only-rule trailing_whitespace \
		--only-rule trailing_newline \
		--only-rule leading_whitespace \
		--only-rule trailing_semicolon \
		$(FIX_PATHS)

clean:
	@rm -rf build dist ; rm -rf ~/Library/Developer/Xcode/DerivedData/ClipboardEnvy-*

# App icon pipeline:
#   1. Composite assets/app-icon-large-transparent.png over assets/app-icon-background-large.png → assets/app-icon-large.png
#   2. Copy assets/app-icon-large.png → AppIcon_1024.png (source for all AppIcon sizes)
#   3. Resize AppIcon_1024 to 16, 32, 64, 128, 256, 512; also emit transparent 128x128 from large-transparent.
APPICON_DIR := ClipboardEnvy/Assets.xcassets/AppIcon.appiconset
APPICON_SRC := $(APPICON_DIR)/AppIcon_1024.png
APPICON_SIZES := 16 32 64 128 256 512
APPICON_BG := assets/app-icon-background-large.png
APPICON_LARGE := assets/app-icon-large.png

# Transparent icon: source of truth is assets/app-icon-large-transparent.png → 128x128 to both:
APPICON_TRANSPARENT_SRC := assets/app-icon-large-transparent.png
APPICON_TRANSPARENT_128 := assets/app-icon-transparent.png
APPICON_TRANSPARENT_IMAGESET := ClipboardEnvy/Assets.xcassets/AppIconTransparent.imageset/app-icon-transparent.png

# Build info generation: BuildInfo.generated.swift used by BuildInfo.swift.
# These defaults can be overridden by environment variables, e.g.:
#   COMMIT=... DATE=... CONFIG=Release ARCH=arm64 make generate-build-info
COMMIT ?= $(shell git rev-parse HEAD 2>/dev/null || echo local)
DATE ?= $(shell date -u +"%Y-%m-%dT%H:%M:%S.000Z")
CONFIG ?= Debug
ARCH ?= arm64

# Override version at build time (e.g. TAGVER=1.0.0-demo make build-release-unsigned).
# Writes ClipboardEnvy/Version.xcconfig so the app shows this version in About and Info.plist.
TAGVER ?=

generate-build-info:
	@printf '// Generated by Makefile - do not edit\nenum BuildInfoGenerated {\n    static let buildCommit = "%s"\n    static let buildDate = "%s"\n    static let buildConfiguration = "%s"\n    static let buildArch = "%s"\n}\n' "$(COMMIT)" "$(DATE)" "$(CONFIG)" "$(ARCH)" > ClipboardEnvy/AppData/BuildInfo.generated.swift

build:
	mkdir -p build
	@if [ -n "$(TAGVER)" ]; then \
		printf 'MARKETING_VERSION = %s\nINFOPLIST_KEY_NSHumanReadableCopyright = Copyright © 2026 Centennial OSS\n' "$(TAGVER)" > ClipboardEnvy/Version.xcconfig; \
	fi
	xcodebuild -scheme ClipboardEnvy -configuration Debug -derivedDataPath build/DerivedData build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
	cp -R "build/DerivedData/Build/Products/Debug/Clipboard Envy.app" build/

build-release-unsigned:
	mkdir -p dist
	@if [ -n "$(TAGVER)" ]; then \
		printf 'MARKETING_VERSION = %s\nINFOPLIST_KEY_NSHumanReadableCopyright = Copyright © 2026 Centennial OSS\n' "$(TAGVER)" > ClipboardEnvy/Version.xcconfig; \
	fi
	xcodebuild -scheme ClipboardEnvy -configuration Release -derivedDataPath dist/DerivedData build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
	cp -R "dist/DerivedData/Build/Products/Release/Clipboard Envy.app" dist/

# Run Swift tests (lint first).
test: lint
	mkdir -p build
	xcodebuild test -scheme ClipboardEnvy -configuration Debug -derivedDataPath build/DerivedData -destination 'platform=macOS' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO

# Generate app icon: composite transparent onto background → app-icon-large.png; copy to AppIcon_1024; then resize.
# Composite uses Swift script (no extra deps on macOS). 16 and 32: center-crop then resize; 64,128,256,512: resize only.
generate-appicons:
	@test -f $(APPICON_BG) || (echo "Missing: $(APPICON_BG)" && exit 1)
	@test -f $(APPICON_TRANSPARENT_SRC) || (echo "Missing: $(APPICON_TRANSPARENT_SRC)" && exit 1)
	@echo "Compositing app-icon-large-transparent.png onto app-icon-background-large.png → app-icon-large.png"
	@swift scripts/composite-app-icon.swift $(APPICON_BG) $(APPICON_TRANSPARENT_SRC) $(APPICON_LARGE)
	@cp $(APPICON_LARGE) $(APPICON_SRC)
	@echo "AppIcon_1024.png updated from app-icon-large.png"
	@test -f $(APPICON_SRC) || (echo "Missing source: $(APPICON_SRC)" && exit 1)
	@for size in $(APPICON_SIZES); do \
		echo "Creating AppIcon_$$size.png from AppIcon_1024.png"; \
		if [ "$$size" = "16" ]; then \
			sips --cropToHeightWidth 780 780 $(APPICON_SRC) --out /tmp/AppIcon_crop.png && \
			sips -z 16 16 /tmp/AppIcon_crop.png --out $(APPICON_DIR)/AppIcon_16.png; \
		elif [ "$$size" = "32" ]; then \
			sips --cropToHeightWidth 880 880 $(APPICON_SRC) --out /tmp/AppIcon_crop.png && \
			sips -z 32 32 /tmp/AppIcon_crop.png --out $(APPICON_DIR)/AppIcon_32.png; \
		else \
			sips -z $$size $$size --out $(APPICON_DIR)/AppIcon_$$size.png $(APPICON_SRC); \
		fi; \
	done
	@rm -f /tmp/AppIcon_crop.png
	@test -f $(APPICON_TRANSPARENT_SRC) || (echo "Missing source: $(APPICON_TRANSPARENT_SRC)" && exit 1)
	@echo "Creating app-icon-transparent.png (128x128) from app-icon-large-transparent.png"
	@sips -z 128 128 $(APPICON_TRANSPARENT_SRC) --out /tmp/app-icon-transparent-128.png
	@cp /tmp/app-icon-transparent-128.png $(APPICON_TRANSPARENT_128)
	@cp /tmp/app-icon-transparent-128.png $(APPICON_TRANSPARENT_IMAGESET)
	@rm -f /tmp/app-icon-transparent-128.png
	@echo "Done writing AppIcons and transparent 128x128"
